### ISSUE TITLE
Too long name of PolymerAutoNotifySupportJsBehavior and PolymerAutoNotifySupportBehavior

### ISSUE THREAD

**Issue by joo** [dam0vm3nt/polymer_autonotify#5]
Please play a short name.

**Comment by dam0vm3nt** [comment]
suggestion ?

**Comment by dam0vm3nt** [comment]
BTW : I hate the current name, so suggestions are welcome.

**Comment by joo** [comment]
^_^
PolymerAutoNotifyJsBehavior  better than PolymerAutoNotifySupportJsBehavior.
More: ObservableJsBehavior, or ObserveJsBehavior, or AutoNotifyJsBehavior.
I like ObservableJsBehavior or ObserveJsBehavior, corresponds Observable.
Because package name is "polymer_autonotity", so the function(or class) name does not contain "polymer".

**Comment by dam0vm3nt** [comment]
You can now use only the  `AutonotifyBehavior` in place of the old two (which are still supported). See tests for a working example.

**Comment by joo** [comment]
Thank you, short of some, it seems the mood well.
